version: '3'

services:
    web:
        container_name: ${DOCKER_NAME}_web
        build:
            context: .
            args:
                user: ${USER}
                uid: ${UID}
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/app
